# Generated by Django 3.2.5 on 2022-04-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=400)),
                ('open_status', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('emotion', models.CharField(max_length=50)),
            ],
        ),
    ]
