# Generated by Django 3.2.5 on 2022-04-21 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET('탈퇴한 사용자'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='books',
            name='emotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.emotion'),
        ),
    ]
