# Generated by Django 3.2.5 on 2022-05-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_storeemotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(default='2022-04-30'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diary',
            name='emotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.emotion'),
        ),
        migrations.AlterField(
            model_name='recommendlist',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.diary'),
        ),
        migrations.AlterField(
            model_name='recommendlist',
            name='rec_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.books'),
        ),
        migrations.AlterField(
            model_name='recommendlist',
            name='rec_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.movies'),
        ),
        migrations.AlterField(
            model_name='recommendlist',
            name='rec_music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.music'),
        ),
    ]
