# Generated by Django 3.2.5 on 2022-04-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20220418_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='emotion',
        ),
    ]
