# Generated by Django 3.2.5 on 2022-04-20 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_diary_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='emotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.emotion'),
        ),
    ]
