# Generated by Django 3.2.5 on 2022-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20220503_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='max_emotion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
