# Generated by Django 3.2.5 on 2022-04-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_diary_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=models.SET('탈퇴한 사용자'), to='mainApp.users'),
        ),
    ]
