# Generated by Django 3.2.5 on 2022-04-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_diary_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='open_status',
            field=models.IntegerField(null=True),
        ),
    ]
