# Generated by Django 3.2.5 on 2022-04-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_diary_open_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
